version: '3.9'

name: e_commerce_backend

services:
  db:
   image: postgres
   container_name: e_commerce_db
   restart: always
   ports:
     - 5432:5432
   environment:
    POSTGRES_PASSWORD: ${DB_PWD}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_DB: ${DB_NAME}
   volumes: 
    - pgdata:/var/lib/postgresql/18/docker
  
  db_client:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
     - pgdata:/var/lib/postgresql/18/docker
  
volumes: 
  pgdata: